# Generated by Django 4.2.29 on 2026-05-04 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_eyebrow", models.CharField(blank=True, max_length=120)),
                ("page_title", models.TextField(blank=True)),
                ("page_lede", models.TextField(blank=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "principles_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "principles_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "whoweserve_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                ("whoweserve_eyebrow", models.CharField(blank=True, max_length=120)),
                ("whoweserve_title", models.CharField(blank=True, max_length=255)),
                ("whoweserve_body", models.TextField(blank=True)),
                (
                    "measure_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                ("measure_section_title", models.CharField(blank=True, max_length=255)),
                ("measure_section_lede", models.TextField(blank=True)),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_url", models.CharField(blank=True, max_length=512)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "About page",
                "verbose_name_plural": "About page",
            },
        ),
        migrations.CreateModel(
            name="ApproachBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ApproachPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_eyebrow", models.CharField(blank=True, max_length=120)),
                ("page_title", models.TextField(blank=True)),
                ("page_lede", models.TextField(blank=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="approach/"),
                ),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_url", models.CharField(blank=True, max_length=512)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Approach page",
                "verbose_name_plural": "Approach page",
            },
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_eyebrow", models.CharField(blank=True, max_length=120)),
                ("page_title", models.TextField(blank=True)),
                ("page_lede", models.TextField(blank=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="contact/"),
                ),
                (
                    "hq_label",
                    models.CharField(
                        blank=True, default="Headquarters", max_length=120
                    ),
                ),
                ("hq_address", models.TextField(blank=True)),
                (
                    "phone_label",
                    models.CharField(blank=True, default="Phone", max_length=120),
                ),
                ("phone_number", models.CharField(blank=True, max_length=64)),
                (
                    "email_label",
                    models.CharField(blank=True, default="Email", max_length=120),
                ),
                ("email_address", models.EmailField(blank=True, max_length=254)),
                (
                    "next_steps_label",
                    models.CharField(blank=True, default="Next steps", max_length=120),
                ),
                ("next_steps_text", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contact page",
                "verbose_name_plural": "Contact page",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("sector", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DftPillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=255)),
                ("blurb", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DigitalFastTrackPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_eyebrow", models.CharField(blank=True, max_length=120)),
                ("page_title", models.TextField(blank=True)),
                ("page_lede", models.TextField(blank=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="dft/"),
                ),
                (
                    "page_cta_primary_label",
                    models.CharField(blank=True, max_length=120),
                ),
                ("page_cta_primary_url", models.CharField(blank=True, max_length=512)),
                (
                    "page_cta_secondary_label",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "page_cta_secondary_url",
                    models.CharField(blank=True, max_length=512),
                ),
                ("why_section_eyebrow", models.CharField(blank=True, max_length=120)),
                ("why_section_title", models.CharField(blank=True, max_length=255)),
                ("why_section_lede", models.TextField(blank=True)),
                (
                    "pillars_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                ("pillars_section_title", models.CharField(blank=True, max_length=255)),
                ("pillars_section_lede", models.TextField(blank=True)),
                (
                    "timeline_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "timeline_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("timeline_section_lede", models.TextField(blank=True)),
                (
                    "outcomes_image",
                    models.ImageField(blank=True, null=True, upload_to="dft/"),
                ),
                ("outcomes_eyebrow", models.CharField(blank=True, max_length=120)),
                ("outcomes_title", models.CharField(blank=True, max_length=255)),
                ("outcomes_body", models.TextField(blank=True)),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_url", models.CharField(blank=True, max_length=512)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Digital Fast Track page",
                "verbose_name_plural": "Digital Fast Track page",
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_eyebrow", models.CharField(blank=True, max_length=255)),
                (
                    "hero_title_lead",
                    models.CharField(
                        blank=True,
                        help_text='The plain part of the hero title — e.g. "Full-service technology services for"',
                        max_length=255,
                    ),
                ),
                (
                    "hero_title_em",
                    models.CharField(
                        blank=True,
                        help_text="The italic/cyan portion of the hero title.",
                        max_length=255,
                    ),
                ),
                ("hero_lede", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                (
                    "hero_cta_primary_label",
                    models.CharField(blank=True, max_length=120),
                ),
                ("hero_cta_primary_url", models.CharField(blank=True, max_length=512)),
                (
                    "hero_cta_secondary_label",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "hero_cta_secondary_url",
                    models.CharField(blank=True, max_length=512),
                ),
                (
                    "pillars_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                ("pillars_section_title", models.CharField(blank=True, max_length=255)),
                ("pillars_section_lede", models.TextField(blank=True)),
                (
                    "ppp_image",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                ("ppp_eyebrow", models.CharField(blank=True, max_length=120)),
                ("ppp_title", models.CharField(blank=True, max_length=255)),
                ("ppp_body", models.TextField(blank=True)),
                (
                    "snapshot_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "snapshot_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "howwework_section_eyebrow",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "howwework_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_url", models.CharField(blank=True, max_length=512)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Home page",
                "verbose_name_plural": "Home page",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                (
                    "favicon",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("footer_tagline", models.TextField(blank=True)),
                ("footer_address", models.TextField(blank=True)),
                ("footer_phone", models.CharField(blank=True, max_length=64)),
                ("footer_email", models.EmailField(blank=True, max_length=254)),
                ("copyright_line", models.CharField(blank=True, max_length=255)),
                ("social_linkedin", models.URLField(blank=True)),
                ("social_x", models.URLField(blank=True)),
                ("social_youtube", models.URLField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "snapshot",
                    models.TextField(
                        blank=True,
                        help_text="Short blurb shown on the Solutions hub and Home snapshot grids.",
                    ),
                ),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="solutions/"),
                ),
                ("hero_title", models.TextField(blank=True)),
                ("hero_lede", models.TextField(blank=True)),
                ("overview_title", models.CharField(blank=True, max_length=255)),
                ("overview_lede", models.TextField(blank=True)),
                (
                    "outcome",
                    models.TextField(
                        blank=True,
                        help_text="Single-sentence outcome focus shown in the highlighted band.",
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="SolutionsPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_eyebrow", models.CharField(blank=True, max_length=120)),
                ("page_title", models.TextField(blank=True)),
                ("page_lede", models.TextField(blank=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="solutions/"),
                ),
                ("section_eyebrow", models.CharField(blank=True, max_length=120)),
                ("section_title", models.CharField(blank=True, max_length=255)),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_url", models.CharField(blank=True, max_length=512)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Solutions hub",
                "verbose_name_plural": "Solutions hub",
            },
        ),
        migrations.CreateModel(
            name="TrainingAdjacency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("snapshot", models.TextField(blank=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="training/"),
                ),
                ("hero_title", models.TextField(blank=True)),
                ("hero_lede", models.TextField(blank=True)),
                ("overview_title", models.CharField(blank=True, max_length=255)),
                ("overview_lede", models.TextField(blank=True)),
                ("outcome", models.TextField(blank=True)),
                ("cta_label", models.CharField(blank=True, max_length=120)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("has_cyber_framework", models.BooleanField(default=False)),
                ("cf_section_eyebrow", models.CharField(blank=True, max_length=120)),
                ("cf_section_title", models.TextField(blank=True)),
                ("cf_section_lede", models.TextField(blank=True)),
                ("cf_foundation_tag", models.CharField(blank=True, max_length=120)),
                ("cf_foundation_title", models.CharField(blank=True, max_length=255)),
                ("cf_foundation_desc", models.TextField(blank=True)),
                (
                    "adjacent",
                    models.ManyToManyField(
                        blank=True,
                        related_name="referenced_by",
                        through="content.TrainingAdjacency",
                        to="content.trainingarea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="TrainingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_eyebrow", models.CharField(blank=True, max_length=120)),
                ("page_title", models.TextField(blank=True)),
                ("page_lede", models.TextField(blank=True)),
                (
                    "page_image",
                    models.ImageField(blank=True, null=True, upload_to="training/"),
                ),
                ("section_eyebrow", models.CharField(blank=True, max_length=120)),
                ("section_title", models.CharField(blank=True, max_length=255)),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_primary_label", models.CharField(blank=True, max_length=120)),
                ("cta_primary_url", models.CharField(blank=True, max_length=512)),
                ("cta_secondary_label", models.CharField(blank=True, max_length=120)),
                ("cta_secondary_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Training hub",
                "verbose_name_plural": "Training hub",
            },
        ),
        migrations.CreateModel(
            name="TrainingDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="content.trainingarea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="trainingadjacency",
            name="from_training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjacent_links",
                to="content.trainingarea",
            ),
        ),
        migrations.AddField(
            model_name="trainingadjacency",
            name="to_training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="adjacent_links_reverse",
                to="content.trainingarea",
            ),
        ),
        migrations.CreateModel(
            name="SolutionDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.TextField()),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="content.solution",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SolutionAdjacency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "from_solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacent_links",
                        to="content.solution",
                    ),
                ),
                (
                    "to_solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjacent_links_reverse",
                        to="content.solution",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("from_solution", "to_solution")},
            },
        ),
        migrations.AddField(
            model_name="solution",
            name="adjacent",
            field=models.ManyToManyField(
                blank=True,
                related_name="referenced_by",
                through="content.SolutionAdjacency",
                to="content.solution",
            ),
        ),
        migrations.CreateModel(
            name="HomeProcessStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_steps",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomePPPBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ppp_bullets",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("link_label", models.CharField(blank=True, max_length=120)),
                ("link_url", models.CharField(blank=True, max_length=512)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillars",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeHeroMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                ("value", models.CharField(max_length=120)),
                ("desc", models.CharField(blank=True, max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_meta",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DftTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="content.digitalfasttrackpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DftPillarPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=500)),
                (
                    "pillar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points",
                        to="content.dftpillar",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="dftpillar",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pillars",
                to="content.digitalfasttrackpage",
            ),
        ),
        migrations.CreateModel(
            name="DftOutcomeBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outcome_bullets",
                        to="content.digitalfasttrackpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DftMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="content.digitalfasttrackpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CyberPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=8)),
                ("label", models.CharField(max_length=120)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cf_phases",
                        to="content.trainingarea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CyberCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "tag",
                    models.CharField(
                        help_text='Match a phase label exactly: "Preparation", "Prevention", "Detection", "Response".',
                        max_length=120,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cf_cards",
                        to="content.trainingarea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactSector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=255)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sectors",
                        to="content.contactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CmsEditorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sections", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cms_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApproachBlockBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=500)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullets",
                        to="content.approachblock",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="approachblock",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blocks",
                to="content.approachpage",
            ),
        ),
        migrations.CreateModel(
            name="AboutWhoBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=500)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="who_bullets",
                        to="content.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutPrinciple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("num", models.CharField(max_length=8)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="principles",
                        to="content.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutMeasureCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_cards",
                        to="content.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="trainingadjacency",
            unique_together={("from_training", "to_training")},
        ),
    ]
