# Generated by Django 4.2.29 on 2026-03-24 23:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_title", models.CharField(blank=True, max_length=255)),
                ("hero_intro", models.TextField(blank=True)),
                (
                    "hero_wave_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                (
                    "differentiators_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("who_heading", models.CharField(blank=True, max_length=255)),
                ("who_body", models.TextField(blank=True)),
                ("outcome_heading", models.CharField(blank=True, max_length=255)),
                ("outcome_subheading", models.CharField(blank=True, max_length=255)),
                ("outcome_body", models.TextField(blank=True)),
                ("outcome_cta_label", models.CharField(blank=True, max_length=120)),
                ("outcome_cta_url", models.CharField(blank=True, max_length=512)),
                (
                    "outcome_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
                ("approach_pill", models.CharField(blank=True, max_length=120)),
                ("approach_heading", models.CharField(blank=True, max_length=255)),
                (
                    "approach_bottom_cta_label",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "approach_bottom_cta_url",
                    models.CharField(blank=True, max_length=512),
                ),
                (
                    "approach_wave_image",
                    models.ImageField(blank=True, null=True, upload_to="about/"),
                ),
            ],
            options={
                "verbose_name": "About page",
            },
        ),
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("badge", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Case studies",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline_gold", models.CharField(blank=True, max_length=255)),
                ("headline_dark", models.CharField(blank=True, max_length=255)),
                ("intro", models.TextField(blank=True)),
                ("submit_label", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "verbose_name": "Contact page",
            },
        ),
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sector", models.CharField(blank=True, max_length=120)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("project_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("quick", "Quick links"),
                            ("sector", "Sectors"),
                            ("legal", "Legal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("url", models.CharField(blank=True, max_length=512)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_eyebrow", models.CharField(blank=True, max_length=120)),
                (
                    "hero_h1",
                    models.TextField(
                        blank=True,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("hero_body", models.TextField(blank=True)),
                (
                    "hero_cta_primary_label",
                    models.CharField(blank=True, max_length=120),
                ),
                ("hero_cta_primary_url", models.CharField(blank=True, max_length=512)),
                (
                    "hero_cta_secondary_label",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "hero_cta_secondary_url",
                    models.CharField(blank=True, max_length=512),
                ),
                (
                    "hero_bg",
                    models.ImageField(blank=True, null=True, upload_to="home/"),
                ),
                ("what_deliver_title", models.CharField(blank=True, max_length=255)),
                ("ppp_heading", models.CharField(blank=True, max_length=255)),
                ("ppp_body", models.TextField(blank=True)),
                (
                    "solutions_snapshot_title",
                    models.CharField(blank=True, max_length=255),
                ),
                ("how_we_work_title", models.CharField(blank=True, max_length=255)),
                ("cta_heading", models.CharField(blank=True, max_length=255)),
                ("cta_body", models.TextField(blank=True)),
                ("cta_button_label", models.CharField(blank=True, max_length=120)),
                ("cta_button_url", models.CharField(blank=True, max_length=512)),
                ("cta_bg", models.ImageField(blank=True, null=True, upload_to="home/")),
            ],
            options={
                "verbose_name": "Home page",
                "verbose_name_plural": "Home page",
            },
        ),
        migrations.CreateModel(
            name="ImpactPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_eyebrow", models.CharField(blank=True, max_length=120)),
                ("headline", models.TextField(blank=True)),
                ("headline_highlight", models.CharField(blank=True, max_length=500)),
                ("metrics_section_title", models.CharField(blank=True, max_length=255)),
                (
                    "case_studies_section_title",
                    models.CharField(blank=True, max_length=255),
                ),
            ],
            options={
                "verbose_name": "Impact page",
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="site/")),
                (
                    "header_image",
                    models.ImageField(blank=True, null=True, upload_to="site/"),
                ),
                ("footer_tagline", models.CharField(blank=True, max_length=255)),
                (
                    "footer_company_line1",
                    models.CharField(default="Peak Global", max_length=120),
                ),
                (
                    "footer_company_line2",
                    models.CharField(default="Partners", max_length=120),
                ),
                ("social_facebook", models.URLField(blank=True)),
                ("social_google", models.URLField(blank=True)),
                ("social_instagram", models.URLField(blank=True)),
                ("social_youtube", models.URLField(blank=True)),
                ("footer_address", models.TextField(blank=True)),
                ("footer_email", models.EmailField(blank=True, max_length=254)),
                ("footer_phone", models.CharField(blank=True, max_length=64)),
                ("copyright_line", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name_plural": "Site settings",
            },
        ),
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("is_published", models.BooleanField(default=True)),
                ("nav_title", models.CharField(blank=True, max_length=255)),
                ("nav_subtitle", models.CharField(blank=True, max_length=255)),
                ("nav_column", models.PositiveSmallIntegerField(default=1)),
                ("nav_order", models.PositiveSmallIntegerField(default=0)),
                ("hero_label", models.CharField(blank=True, max_length=120)),
                ("title_black_1", models.CharField(blank=True, max_length=255)),
                ("title_black_2", models.CharField(blank=True, max_length=255)),
                ("title_yellow", models.CharField(blank=True, max_length=255)),
                ("overview_text", models.TextField(blank=True)),
                ("outcome_headline", models.TextField(blank=True)),
                ("outcome_cta", models.CharField(blank=True, max_length=255)),
                ("outcome_cta_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "ordering": ["nav_column", "nav_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hero_label", models.CharField(blank=True, max_length=120)),
                ("title_black_1", models.CharField(blank=True, max_length=255)),
                ("title_black_2", models.CharField(blank=True, max_length=255)),
                ("title_yellow", models.CharField(blank=True, max_length=255)),
                ("overview_text", models.TextField(blank=True)),
                (
                    "overview_sidebar_label",
                    models.CharField(default="Overview", max_length=64),
                ),
                ("domains_heading", models.CharField(blank=True, max_length=255)),
                ("enablement_heading", models.CharField(blank=True, max_length=255)),
                ("outcome_eyebrow", models.CharField(blank=True, max_length=120)),
                ("outcome_headline", models.TextField(blank=True)),
                ("outcome_cta_label", models.CharField(blank=True, max_length=255)),
                ("outcome_cta_url", models.CharField(blank=True, max_length=512)),
            ],
            options={
                "verbose_name": "Technology page",
            },
        ),
        migrations.CreateModel(
            name="TrainingArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("is_published", models.BooleanField(default=True)),
                ("featured", models.BooleanField(default=False)),
                ("hub_subtitle", models.CharField(blank=True, max_length=500)),
                ("hub_order", models.PositiveSmallIntegerField(default=0)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description_start", models.TextField(blank=True)),
                ("highlighted_text", models.CharField(blank=True, max_length=500)),
                ("description_end", models.TextField(blank=True)),
                (
                    "deliver_section_title",
                    models.CharField(default="WHAT WE DELIVER", max_length=120),
                ),
                (
                    "display_style",
                    models.CharField(
                        choices=[
                            ("emoji", "Emoji / icon box"),
                            ("numbered", "Numbered (forensics)"),
                        ],
                        default="emoji",
                        max_length=32,
                    ),
                ),
                ("outcome_tag", models.CharField(blank=True, max_length=120)),
                ("outcome_title", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["hub_order", "slug"],
            },
        ),
        migrations.CreateModel(
            name="TrainingNavItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, max_length=500)),
                ("path", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TrainingCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("icon_emoji", models.CharField(blank=True, max_length=32)),
                ("title", models.CharField(max_length=500)),
                ("subtitle", models.TextField(blank=True)),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="content.trainingarea",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyEnablementItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.TextField()),
                ("icon_key", models.CharField(blank=True, max_length=64)),
                (
                    "tech_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enablement_items",
                        to="content.technologypage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TechnologyDomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("wide", models.BooleanField(default=False)),
                ("icon_key", models.CharField(blank=True, max_length=64)),
                (
                    "tech_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="content.technologypage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SolutionSnapshotCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="solutions/snap/"
                    ),
                ),
                (
                    "hover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="solutions/snap/"
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshot_cards",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SolutionDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("code", models.CharField(blank=True, max_length=8)),
                ("text", models.TextField()),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to="content.solution",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ImpactMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("stat", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=255)),
                ("wide", models.BooleanField(default=False)),
                (
                    "impact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="content.impactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomePillar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pillars",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="HomeHowStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=500)),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="how_steps",
                        to="content.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ContactSectorOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                ("value", models.SlugField(max_length=64)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_options",
                        to="content.contactpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CaseStudyQuadrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=120)),
                ("body", models.TextField(blank=True)),
                (
                    "case_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quadrants",
                        to="content.casestudy",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="casestudy",
            name="impact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_studies",
                to="content.impactpage",
            ),
        ),
        migrations.CreateModel(
            name="AboutDifferentiatorCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="about/icons/"),
                ),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="differentiator_cards",
                        to="content.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="AboutApproachStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("number", models.CharField(default="1", max_length=8)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("bullets", models.JSONField(blank=True, default=list)),
                (
                    "about",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="approach_steps",
                        to="content.aboutpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
