# Generated by Django 4.2.29 on 2026-05-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpage",
            name="page_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="aboutpage",
            name="whoweserve_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="approachpage",
            name="page_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="contactpage",
            name="page_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="digitalfasttrackpage",
            name="outcomes_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="digitalfasttrackpage",
            name="page_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hero_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="ppp_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="solution",
            name="hero_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="solutionspage",
            name="page_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="trainingarea",
            name="hero_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="trainingpage",
            name="page_image_url",
            field=models.CharField(
                blank=True,
                help_text="Static path or absolute URL — used in place of the uploaded file when set.",
                max_length=512,
            ),
        ),
    ]
